#include <iostream>

using namespace std;

void Xtest (int test) {
  cout << "В функции Xtest(), значение test равно: " << test <<"\n";
  if (test) throw test;
}

int main() {
  cout << "Начало\n";
  try { // начало try-блока
  cout << "В try-блоке\n";
  Xtest(0);
  Xtest(1);
  Xtest(2);
}
catch (int i) { //перехват ошибки
  cout << "Перехват искючения. Его значение равно: ";
  cout << i << "\n";
}
  cout << "Конец";
return 0;
}
